[package]
name = "cactpot"
version = "0.1.0"
edition = "2024"
resolver = "2"

[dependencies]
yew = { version = "0.21", features = ["csr"] }
wasm-bindgen = "0.2"
web-sys = "0.3.77"
itertools = "0.14.0"

[profile.release]
lto = true
codegen-units = 1
opt-level = 'z'
panic = 'abort'
strip = true
