name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-binstall
        run: |
          curl -LsSf https://github.com/cargo-bins/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-unknown-linux-gnu.tar.gz | tar xz -C $HOME/.cargo/bin
          chmod +x $HOME/.cargo/bin/cargo-binstall

      - name: Install Trunk with cargo-binstall
        run: cargo binstall --no-confirm trunk

      - name: Install wasm32 target
        run: rustup target add wasm32-unknown-unknown

      - name: Build with Trunk
        run: trunk build --release --public-url /${{ github.event.repository.name }}/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
